output:
  folder: output/acc_vs_loss/mnist_guess_uniform
  target_model_count: 2000
dataset:
  name: mnist
  mnistcifar:
    num_classes: 2
    classes: "0,7"
model:
  arch: lenet
  lenet:
    width: 0.5
  model_count_times_batch_size: 1600000 # Old 16000
  normalization: lipschitz
  init: uniform
optimizer:
  name: guess
distributed:
  loss_thres: "-999,999"
  num_samples: "16"
  data_seed: 0
  target_model_count_subrun: 30 # Old 100
